apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-url
spec:
  rules:
  - http:
      paths:
      - path: /server
        pathType: Prefix
        backend:
          service:
            name: server-srv
            port:
              number: 80
