apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  # revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: echo:1.0.0
        name: echo-app
        ports:
        - containerPort: 3000
----
apiVersion: v1
kind: Service
metadata:
  name: echo-srv
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: echo
----
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-url
spec:
  rules:
  - http:
      paths:
      - path: /echo
        pathType: Prefix
        backend:
          service:
            name: echo-srv
            port:
              number: 80
